#!/bin/bash
echo "Running `basename "$0"`"

# Build alias maps
jq -r '.domains | .[] | select(.[0] != null) | .[] | select(has("aliases")) | .alias as $email | .aliases | .[] | [., $email] | join("\t")' "$CONFIG_FILE" > /etc/postfix/virtual
# Build domain maps
jq -r '.domains | keys | .[]' "$CONFIG_FILE" > /etc/postfix/virtual-mailbox-domains
# Build mailbox maps
jq -r '.domains | .[] | select(.[0] != null) | .[] | select(.password != null) | .email' "$CONFIG_FILE" | sed -e 's|\(.*\)@\(.*\)|\0\t\2/\1/|' > /etc/postfix/virtual-mailbox-maps
# Build blacklist (receiver)
jq -r '.blacklist | .[]' "$CONFIG_FILE" | sed -e 's/$/\tREJECT You are permanently banned/' > /etc/postfix/receiver_blacklist
# Build blacklist (sender)
jq -r '.sender_blacklist | .[]' "$CONFIG_FILE" | sed -e 's/$/\tREJECT You are permanently banned/' > /etc/postfix/sender_blacklist

# Process alias, blacklist and mailbox maps
postmap /etc/postfix/blacklist
postmap /etc/postfix/virtual
postmap /etc/postfix/virtual-mailbox-maps

# Give postfix ownership of its files
chown -R postfix:postfix /etc/postfix
chown root:root /etc/postfix/dynamicmaps.cf
chmod 640 /etc/postfix/dynamicmaps.cf

# Give vmail ownership of all mail folders
chown -R vmail:vmail /vmail
chmod u+w /vmail

# Build a password file
jq -r '.domains | .[] | select(.[0] != null) | .[] | select(.password != null) | [.email, .password] | join(":")' "$CONFIG_FILE" > /etc/dovecot/passwd
